---
version: "3"

services:

  jet-server-1:
    container_name: jet-server-1
    image: hazelcast/hazelcast-jet-enterprise@sha256:bef554c744d89f71be147bb42f658e4d68745d159a99f51c474b2827091fe74a
    volumes:
      - ".:/opt/project"
    environment:
      CITY_DATA_FILE: /opt/project/data/mapdata.csv
    command: >
      java
      -cp /opt/project/jet-server/target/jet-server-1.0-SNAPSHOT.jar:/opt/project/vehicle-monitor-pipeline/target/vehicle-monitor-pipeline-1.0-SNAPSHOT.jar:/opt/project/ingest-pipeline/target/ingest-pipeline-1.0-SNAPSHOT.jar
      -Dhazelcast.config=/opt/project/config/hazelcast.xml
      -Dhazelcast.jet.config=/opt/project/config/hazelcast-jet.xml
      -Dhazelcast.enterprise.license.key=${JET_LICENSE_KEY}
      -Dhazelcast.logging.type=log4j2
      -Dlog4j2.configurationFile=/opt/project/config/log4j2.xml
      com.hazelcast.training.streams.server.Server

  jet-server-2:
    container_name: jet-server-2
    image: hazelcast/hazelcast-jet-enterprise@sha256:bef554c744d89f71be147bb42f658e4d68745d159a99f51c474b2827091fe74a
    volumes:
      - ".:/opt/project"
    environment:
      CITY_DATA_FILE: /opt/project/data/mapdata.csv
    command: >
      java
      -cp /opt/project/jet-server/target/jet-server-1.0-SNAPSHOT.jar:/opt/project/vehicle-monitor-pipeline/target/vehicle-monitor-pipeline-1.0-SNAPSHOT.jar:/opt/project/ingest-pipeline/target/ingest-pipeline-1.0-SNAPSHOT.jar
      -Dhazelcast.config=/opt/project/config/hazelcast.xml
      -Dhazelcast.jet.config=/opt/project/config/hazelcast-jet.xml
      -Dhazelcast.enterprise.license.key=${JET_LICENSE_KEY}
      -Dhazelcast.logging.type=log4j2
      -Dlog4j2.configurationFile=/opt/project/config/log4j2.xml
      com.hazelcast.training.streams.server.Server

#  jet-server-3:
#    container_name: jet-server-3
#    image: hazelcast/hazelcast-jet-enterprise@sha256:95138f113992b8a98865cc42af59b918b1a9edff4f2d70850f69d8e29996b5cb
#    volumes:
#      - ".:/opt/project"
#    environment:
#      CITY_DATA_FILE: /opt/project/data/mapdata.csv
#    command: >
#      java
#      -cp /opt/project/jet-server/target/jet-server-1.0-SNAPSHOT.jar
#      -Dhazelcast.config=/opt/project/config/hazelcast.xml
#      -Dhazelcast.jet.config=/opt/project/config/hazelcast-jet.xml
#      -Dhazelcast.enterprise.license.key=${JET_LICENSE_KEY}
#      -Dhazelcast.logging.type=log4j2
#      -Dlog4j2.configurationFile=/opt/project/config/log4j2.xml
#      com.hazelcast.training.streams.server.Server



  fleetsim-beta:
    container_name: fleetsim-beta
    build:
      context: docker-images/hazelcast-python
    volumes:
      - ".:/opt/project"
    working_dir: /opt/project/data
    ports:
      - 8000:8000
    environment:
      FLASK_APP: fleetsim_beta
    command: flask run -h 0.0.0.0 -p 8000

  fleetsim-alpha:
    container_name: fleetsim-alpha
    build:
      context: docker-images/hazelcast-python
    volumes:
      - ".:/opt/project"
    working_dir: /opt/project/data
    command: python fleetsim_alpha.py

  mapserver:
    container_name: mapserver
    build:
      context: docker-images/hazelcast-python
    volumes:
      - ".:/opt/project"
    ports:
      - 5006:5006
    command: >
      bokeh serve /opt/project/UI/dashboard.py

  imdg-management-center:
    container_name: imdg-management-center
    image: hazelcast/management-center@sha256:52ea78110f7cf4d129d73133606dd35796a61e47728a72b5fe805fc210fa34d1
    volumes:
      - "./mc-home:/data"
    ports:
      - 8080:8080

  jet-management-center:
    container_name: jet-management-center
    image: hazelcast/hazelcast-jet-management-center@sha256:532f625637adbd576f224d971c76c94d2f44fd37491c57ac689965b4e70d40b5
    environment:
      MC_CLIENT_CONFIG: /opt/project/config/hazelcast-client.xml
      MC_LICENSE_KEY: ${JET_LICENSE_KEY}
    volumes:
      - ".:/opt/project"
    ports:
      - 8081:8081
