---
version: "3"

services:

  jet-server-1:
    container_name: jet-server-1
    networks:
      ids_net:
        ipv4_address: 192.168.1.101
    image: hazelcast/hazelcast-jet-enterprise@sha256:95138f113992b8a98865cc42af59b918b1a9edff4f2d70850f69d8e29996b5cb
    volumes:
      - ".:/opt/project"
    command: >
      java
      -Xmx128m
      -cp /opt/project/jet-server/target/jet-server-1.0-SNAPSHOT.jar
      -Dhazelcast.config=/opt/project/config/hazelcast.xml
      -Dhazelcast.jet.config=/opt/project/config/hazelcast-jet.xml
      -Dhazelcast.enterprise.license.key=${JET_LICENSE_KEY}
      -Dhazelcast.logging.type=log4j2
      -Dlog4j2.configurationFile=/opt/project/config/log4j2.xml
      com.hazelcast.training.streams.server.Server

  jet-server-2:
    container_name: jet-server-2
    networks:
      ids_net:
        ipv4_address: 192.168.1.102
    image: hazelcast/hazelcast-jet-enterprise@sha256:95138f113992b8a98865cc42af59b918b1a9edff4f2d70850f69d8e29996b5cb
    volumes:
      - ".:/opt/project"
    command: >
      java
      -Xmx128m
      -cp /opt/project/jet-server/target/jet-server-1.0-SNAPSHOT.jar
      -Dhazelcast.config=/opt/project/config/hazelcast.xml
      -Dhazelcast.jet.config=/opt/project/config/hazelcast-jet.xml
      -Dhazelcast.enterprise.license.key=${JET_LICENSE_KEY}
      -Dhazelcast.logging.type=log4j2
      -Dlog4j2.configurationFile=/opt/project/config/log4j2.xml
      com.hazelcast.training.streams.server.Server

  admin-server:
    container_name: admin-server
    networks:
      ids_net:
        ipv4_address: 192.168.1.99
    image: hazelcast/hazelcast-jet-enterprise@sha256:95138f113992b8a98865cc42af59b918b1a9edff4f2d70850f69d8e29996b5cb
    volumes:
      - ".:/opt/project"
    command: echo EXITING

  fleetsim-beta:
    container_name: fleetsim-beta
    networks:
      ids_net:
        ipv4_address: 192.168.1.121
    build:
      context: docker-images/hazelcast-python
    volumes:
      - ".:/opt/project"
    working_dir: /opt/project/data
    ports:
      - 8000:8000
    environment:
      FLASK_APP: fleetsim_beta
    command: flask run -h 0.0.0.0 -p 8000

  fleetsim-alpha:
    container_name: fleetsim-alpha
    networks:
      ids_net:
        ipv4_address: 192.168.1.122
    build:
      context: docker-images/hazelcast-python
    volumes:
      - ".:/opt/project"
    working_dir: /opt/project/data
    command: python fleetsim_alpha.py

  mapserver:
    container_name: mapserver
    networks:
      ids_net:
        ipv4_address: 192.168.1.123
    build:
      context: docker-images/hazelcast-python
    volumes:
      - ".:/opt/project"
    ports:
      - 5006:5006
    command: >
      bokeh serve /opt/project/UI/dashboard.py

  imdg-management-center:
    container_name: imdg-management-center
    networks:
      ids_net:
        ipv4_address: 192.168.1.124
    image: hazelcast/management-center@sha256:52ea78110f7cf4d129d73133606dd35796a61e47728a72b5fe805fc210fa34d1
    volumes:
      - "./mc-home:/data"
    ports:
      - 8080:8080

  jet-management-center:
    container_name: jet-management-center
    networks:
      ids_net:
        ipv4_address: 192.168.1.125
    image: hazelcast/hazelcast-jet-management-center@sha256:532f625637adbd576f224d971c76c94d2f44fd37491c57ac689965b4e70d40b5
    environment:
      MC_CLIENT_CONFIG: /opt/project/config/hazelcast-client.xml
      MC_LICENSE_KEY: ${JET_LICENSE_KEY}
    volumes:
      - ".:/opt/project"
    ports:
      - 8081:8081

networks:
  ids_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"
